name: Build Android APK

on:
  push:
    branches:
      - android
    # triggered from
    paths:
      - 'frontend/android/**'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # setup JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with: 
          distribution: 'zulu'
          java-version: '17'

      # setup SDK
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # write env
      - name: Create .env from secrets
        working-directory: ./frontend/android
        env:
          ENV_SECRET: ${{ secrets.ANDROID_ENV }} 
        run:
          echo "$ENV_SECRET" > .env

      # go to /frontend & install dependencies
      - name: Install Dependencies
        working-directory: ./frontend/android
        run : flutter pub get
      
      # error analyze
      - name: Code analyze
        id: analyze
        working-directory: ./frontend/android
        run : flutter analyze

      # handling error
      - name: Handling error
        if: failure() && steps.analyze.outcome == 'failure'
        run: |
          echo "Bug found when analyze the code"
          echo "Build canceled"

      # build apk
      - name: Build APK
        if: success()
        working-directory: ./frontend/android
        run : |
          flutter build apk --release

      # Upload Artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: frontend/android/build/app/outputs/flutter-apk/app-release.apk