name: Deploy Hidocs (Backend, Frontend & Database) to VPS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/web/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 30m
          command_timeout: 30m
          script: |
            # Make Directory for Hidocs
            mkdir -p /root/hidocs
            cd /root/hidocs

            # Clone Repository or Pull latest changes
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git remote set-url origin https://github.com/${{ github.repository }}.git
              git fetch origin main
              git reset --hard origin/main
            fi

            # Write .env file
            cat << 'EOF' > .env
            ${{ secrets.ENV_FILE }}
            EOF

            # Build and Run Docker Compose
            docker compose build --no-cache
            docker compose up -d --build
